import React from 'react';
import ReactMarkdown from 'react-markdown';
import { FileText, Download, Copy, Check, RotateCw, X, ChevronLeft } from 'lucide-react';
import ExportMenu from './ExportMenu';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export default function ReportViewer({ markdown, onRegenerate, onClose }) {
    const reportRef = React.useRef(null);
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(markdown);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const blob = new Blob([markdown], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `report-${Date.now()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    if (!markdown) {
        return (
            <div className="flex flex-col items-center justify-center h-full text-gray-500">
                <FileText size={48} className="mb-4 opacity-20" />
                <p>No report generated yet.</p>
                {onRegenerate && (
                    <button
                        onClick={onRegenerate}
                        className="mt-4 px-4 py-2 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-400 text-sm font-medium rounded-xl transition-all"
                    >
                        Try generating again
                    </button>
                )}
            </div>
        );
    }

    const handleExport = (format) => {
        if (format === 'md') {
            const blob = new Blob([markdown], { type: 'text/markdown' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `report-${Date.now()}.md`;
            a.click();
            URL.revokeObjectURL(url);
        } else if (format === 'pdf') {
            const input = document.getElementById('report-content');
            if (input) {
                html2canvas(input, {
                    scale: 2,
                    backgroundColor: '#ffffff', // White for PDF
                    useCORS: true
                }).then((canvas) => {
                    const imgData = canvas.toDataURL('image/png');
                    const pdf = new jsPDF('p', 'mm', 'a4');
                    const pdfWidth = pdf.internal.pageSize.getWidth();
                    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

                    // Branded Background Header for PDF
                    pdf.setFillColor(59, 130, 246); // Blue-500
                    pdf.rect(0, 0, 210, 10, 'F');
                    pdf.setFontSize(8);
                    pdf.setTextColor(255, 255, 255);
                    pdf.text("FLASHDECK AI - DEEP RESEARCH REPORT", 15, 6);

                    pdf.addImage(imgData, 'PNG', 0, 15, pdfWidth, pdfHeight);

                    // Branding on bottom
                    pdf.setTextColor(150, 150, 150);
                    pdf.text("Generated by FlashDeck AI Labs", 150, 285);

                    pdf.save(`FlashDeck_Report_${Date.now()}.pdf`);
                });
            }
        }
    };

    return (
        <div className="h-full flex flex-col bg-[#0a0a0a] rounded-[40px] border border-white/5 overflow-hidden shadow-2xl">
            {/* Header */}
            <div className="flex items-center justify-between px-8 py-6 bg-[#0d0d0d]/80 backdrop-blur-md border-b border-white/5">
                <div className="flex items-center gap-4">
                    {onClose && (
                        <button
                            onClick={onClose}
                            className="mr-2 p-2 hover:bg-white/5 rounded-xl text-gray-400 hover:text-white transition-all transform hover:scale-110"
                        >
                            <ChevronLeft size={20} />
                        </button>
                    )}
                    <div className="w-12 h-12 rounded-2xl bg-blue-500/10 flex items-center justify-center text-blue-400 border border-blue-500/10 shadow-inner">
                        <FileText size={24} />
                    </div>
                    <div>
                        <span className="text-[10px] font-bold text-gray-500 uppercase tracking-[0.3em] block leading-none mb-1">Advanced Synthesis</span>
                        <span className="text-lg font-bold text-white font-heading tracking-tight">Intelligence Report</span>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <ExportMenu onExport={handleExport} type="report" />
                    {onRegenerate && (
                        <button
                            onClick={onRegenerate}
                            className="w-10 h-10 flex items-center justify-center hover:bg-white/5 rounded-xl text-gray-400 hover:text-white transition-all border border-white/5"
                            title="Regenerate"
                        >
                            <RotateCw size={16} />
                        </button>
                    )}
                    <button
                        onClick={handleCopy}
                        className="w-10 h-10 flex items-center justify-center hover:bg-white/5 rounded-xl text-gray-400 hover:text-white transition-all border border-white/5"
                        title="Copy Markdown"
                    >
                        {copied ? <Check size={16} className="text-green-500" /> : <Copy size={16} />}
                    </button>
                    <button
                        onClick={handleDownload}
                        className="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-white text-[11px] font-bold rounded-[18px] transition-all shadow-xl shadow-blue-500/20 flex items-center gap-2 uppercase tracking-wider"
                    >
                        <Download size={14} />
                        Snapshot MD
                    </button>
                </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto custom-scrollbar p-10 md:p-16 bg-dots">
                <div id="report-content" className="prose prose-invert prose-lg max-w-4xl mx-auto font-heading leading-relaxed">
                    <ReactMarkdown>{markdown}</ReactMarkdown>
                </div>

                <div className="mt-20 pt-10 border-t border-white/5 flex items-center justify-between opacity-30">
                    <div className="text-[10px] font-bold text-gray-500 uppercase tracking-[0.4em]">Proprietary Analysis • FlashDeck AI</div>
                    <div className="text-[10px] font-mono text-gray-500">{new Date().toLocaleDateString()}</div>
                </div>
            </div>
        </div>
    );
}
