import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, FileText, Bookmark, Share2, Printer, Clock, FileType, Presentation } from 'lucide-react';
import jsPDF from 'jspdf';
import { saveAs } from 'file-saver';

export default function SavedNotesModal({ isOpen, onClose, notes }) {
    if (!isOpen) return null;

    const stripMarkdown = (text) => {
        if (!text) return "";
        return text
            .replace(/\*\*(.*?)\*\*/g, '$1') // Bold
            .replace(/\*(.*?)\*/g, '$1')     // Italic
            .replace(/__(.*?)__/g, '$1')     // Underline
            .replace(/`(.*?)`/g, '$1')       // Inline code
            .replace(/```[\s\S]*?```/g, '$1')// Code blocks (naive)
            .replace(/#+\s/g, '')            // Headers
            .replace(/>\s/g, '')             // Blockquotes
            .replace(/\[(.*?)\]\(.*?\)/g, '$1') // Links
            .replace(/!\[(.*?)\]\(.*?\)/g, '$1') // Images
            .replace(/-\s/g, '• ')           // Lists
            .trim();
    };

    const exportToTXT = () => {
        const content = notes.map(note => `--- Note (${new Date(note.date).toLocaleString()}) ---\n\n${note.content}\n\n`).join('\n');
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        saveAs(blob, `FlashDeck_Notes_${Date.now()}.txt`);
    };

    const exportToPDF = () => {
        const doc = new jsPDF();
        const brandColor = [99, 102, 241]; // Indigo-500
        let yOffset = 20;

        // Branding Header
        doc.setFillColor(brandColor[0], brandColor[1], brandColor[2]);
        doc.rect(0, 0, 210, 20, 'F');
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(255, 255, 255);
        doc.text("FLASHDECK AI - KNOWLEDGE BANK", 15, 13);

        doc.setFontSize(24);
        doc.setTextColor(30, 41, 59);
        doc.text('Saved Notes', 15, 45);

        doc.setDrawColor(200, 200, 200);
        doc.line(15, 50, 195, 50);

        yOffset = 60;

        notes.forEach((note, index) => {
            const cleanContent = stripMarkdown(note.content);
            const dateStr = new Date(note.date).toLocaleString();

            // Check page break for header
            if (yOffset > 250) {
                doc.addPage();
                yOffset = 20;
            }

            // Note Header
            doc.setFontSize(11);
            doc.setTextColor(99, 102, 241); // Indigo text
            doc.setFont("helvetica", "bold");
            doc.text(`Note ${index + 1} • ${dateStr}`, 15, yOffset);
            yOffset += 7;

            // Content
            doc.setFontSize(10);
            doc.setTextColor(51, 65, 85); // Slate-700
            doc.setFont("helvetica", "normal");

            const splitText = doc.splitTextToSize(cleanContent, 180);

            // Render text line by line to handle page breaks
            splitText.forEach(line => {
                if (yOffset > 275) {
                    doc.addPage();
                    yOffset = 20;
                }
                doc.text(line, 15, yOffset);
                yOffset += 6;
            });

            yOffset += 10;

            // Separator
            doc.setDrawColor(240, 240, 240);
            doc.line(15, yOffset, 195, yOffset);
            yOffset += 10;
        });

        // Branding Footer on all pages
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text("Generated by FlashDeck AI Pro", 105, 290, { align: 'center' });
        }

        doc.save(`FlashDeck_Notes_${Date.now()}.pdf`);
    };

    const exportToPPT = async () => {
        const pptxgen = (await import('pptxgenjs')).default;
        const pres = new pptxgen();
        const brandColor = '6366f1';

        // Title Slide
        const titleSlide = pres.addSlide();
        titleSlide.background = { color: '0f172a' };
        titleSlide.addText("Saved Notes Collection", { x: 1, y: '40%', w: '80%', fontSize: 44, color: 'ffffff', bold: true, align: 'center' });
        titleSlide.addText(`FlashDeck AI Knowledge Bank • ${notes.length} Notes`, { x: 1, y: '55%', w: '80%', fontSize: 18, color: 'adb5bd', align: 'center' });

        notes.forEach((note, index) => {
            const slide = pres.addSlide();
            slide.background = { color: "f8fafc" };
            const cleanContent = stripMarkdown(note.content);

            // Header bar
            slide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 1.0, fill: { color: brandColor } });
            slide.addText(`Note ${index + 1}`, { x: 0.5, y: 0.1, w: 5, fontSize: 24, color: 'ffffff', bold: true });
            slide.addText(new Date(note.date).toLocaleString(), { x: 0.5, y: 0.55, fontSize: 12, color: 'e0e7ff' });

            // Content
            slide.addText(cleanContent, {
                x: 0.5, y: 1.5, w: 9, h: 4,
                fontSize: 14, color: '334155', valign: 'top'
            });

            slide.addText("FlashDeck AI Pro", { x: 0.5, y: 5.2, fontSize: 10, color: '94a3b8' });
        });

        pres.writeFile({ fileName: `FlashDeck_Notes_${Date.now()}.pptx` });
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8 bg-black/60 backdrop-blur-sm">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    className="bg-[#121212] border border-white/10 rounded-[32px] w-full max-w-4xl h-[85vh] flex flex-col shadow-2xl overflow-hidden relative"
                >
                    <div className="absolute inset-0 bg-dots opacity-[0.2] pointer-events-none" />

                    {/* Header */}
                    <div className="flex items-center justify-between px-8 py-6 bg-[#0d0d0d]/80 backdrop-blur-md border-b border-white/5 z-10">
                        <div className="flex items-center gap-4">
                            <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 flex items-center justify-center text-indigo-400 border border-indigo-500/10 shadow-inner">
                                <Bookmark size={24} />
                            </div>
                            <div>
                                <span className="text-[10px] font-bold text-gray-500 uppercase tracking-[0.3em] block leading-none mb-1">Knowledge Bank</span>
                                <h2 className="text-xl font-bold text-white font-heading tracking-tight">Saved Insights ({notes.length})</h2>
                            </div>
                        </div>
                        <button onClick={onClose} className="p-2 text-gray-500 hover:text-white hover:bg-white/5 rounded-full transition-colors">
                            <X size={24} />
                        </button>
                    </div>

                    {/* Content */}
                    <div className="flex-1 overflow-y-auto custom-scrollbar p-8 z-0">
                        {notes.length === 0 ? (
                            <div className="h-full flex flex-col items-center justify-center text-gray-500 space-y-4">
                                <Bookmark size={48} className="opacity-20" />
                                <p>No saved notes yet.</p>
                            </div>
                        ) : (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {notes.map((note, idx) => (
                                    <div key={idx} className="bg-white/5 border border-white/5 rounded-2xl p-6 hover:border-indigo-500/30 transition-all group relative">
                                        <div className="flex items-center justify-between mb-4">
                                            <div className="flex items-center gap-2 text-xs text-gray-400">
                                                <Clock size={12} />
                                                <span>{new Date(note.date).toLocaleString()}</span>
                                            </div>
                                            <div className="flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                                {/* Actions like delete could go here */}
                                            </div>
                                        </div>
                                        <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap font-medium">
                                            {note.content}
                                        </p>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>

                    {/* Footer Actions */}
                    <div className="px-8 py-6 bg-[#0d0d0d]/80 backdrop-blur-md border-t border-white/5 z-10 flex flex-wrap gap-3 items-center justify-between">
                        <div className="text-xs text-gray-500">
                            Export your knowledge bank for offline study.
                        </div>
                        <div className="flex gap-3">
                            <button onClick={exportToPDF} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 text-white rounded-xl text-sm font-medium transition-colors border border-white/5">
                                <FileType size={16} /> PDF
                            </button>
                            <button onClick={exportToPPT} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 text-white rounded-xl text-sm font-medium transition-colors border border-white/5">
                                <Presentation size={16} /> PPTX
                            </button>
                            <button onClick={exportToTXT} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 text-white rounded-xl text-sm font-medium transition-colors border border-white/5">
                                <FileText size={16} /> TXT
                            </button>
                        </div>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
}
